version: "3.9"

services:
  calculator_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  calculator_ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
